name: "zenn-article-fetcher"
description: ""
author: "ryohidaka"
inputs:
  user-id:
    description: ZennのユーザID (https://zenn.dev/{user-id}/feed)
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "file-text"
  color: "green"
