name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "dist/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm ci
          npm run build --if-present

      - name: Commit files
        run: |
          git fetch
          git pull
          git config --local user.email "GitHub Actions"
          git config --local user.name "actions@github.com"
          git add dist
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: Update dist" -n
            git push
          fi
