name: Test Action

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

permissions:
  contents: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Fetch ZennArticles
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch ZennArticles
        uses: ./ # Uses an action in the root directory
        with:
          user-id: "hidaka"
          output: "example/zenn.md"
          template: "- [%DATE% %TITLE%](%LINK%)"
          date-format: "short"
